version: '3.9'
services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    networks:
      - backend-network
    #volumes:
    # - ./nginx:/etc/nginx/conf.d/ # Mount the nginx config file
    depends_on:
      - nodejs-app-1
      - nodejs-app-2
      - mongodb
      - redis

  nodejs-app-1:
    restart: on-failure
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nodejs-app-1
    ports:
      - '81:5000'
    networks:
      - backend-network
    volumes:
      - ./server:/usr/src/app # Mount the app folder

  nodejs-app-2:
    restart: on-failure
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nodejs-app-2
    environment:
      - PORT=5000
    ports:
      - '82:5000'
    networks:
      - backend-network
    volumes:
      - ./server:/usr/src/app # Mount the app folder

  mongodb:
    image: mongo
    container_name: nginx-mongodb
    environment:
      - PUID=1000
    volumes:
      - mongodb-data:/data/db # mongodb voulme to persist data between restarts
      - ./server/mongodb/database:/data/db # Mount the database folder to host ./server/mongodb/database
    ports:
      - 27017:27017
    networks:
      - backend-network
    restart: unless-stopped

  redis:
    image: redis
    container_name: nginx-redisdb
    restart: unless-stopped
    networks:
      - backend-network
    ports:
      - 6379:6379
    volumes:
      - ./server/redis/data:/data # Mount the redis data folder to host ./server/redis/data

networks:
  backend-network:


volumes:
  mongodb-data:
